import type React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  container: { maxWidth: 480, margin: "0 auto", background: "var(--bg-primary)", minHeight: "100vh", fontFamily: "'Inter', 'Poppins', sans-serif", position: "relative", paddingBottom: 140 },
  header: { background: "#333", color: "#fff", display: "flex", justifyContent: "space-between", alignItems: "center", padding: "14px 16px" },
  headerLeft: { display: "flex", alignItems: "center", gap: 8 },
  headerTitle: { fontSize: 20, fontWeight: 700 },
  headerRight: { display: "flex", gap: 16 },
  iconBtn: { background: "none", border: "none", color: "#fff", fontSize: 20, cursor: "pointer", display: "flex", alignItems: "center" },
  profileRow: { display: "flex", alignItems: "center", padding: "12px 16px", gap: 12 },
  avatar: { width: 48, height: 48, borderRadius: "50%", background: "#f0e6d3", border: "2px solid #c9a96e", display: "flex", alignItems: "center", justifyContent: "center", color: "#c9a96e" },
  deliveryToggle: { flex: 1 },
  deliveryBtn: { background: "none", border: "none", fontSize: 14, color: "var(--text-secondary)", cursor: "pointer", padding: "6px 12px", display: "flex", alignItems: "center", gap: 4 },
  deliveryActive: { background: "none", border: "none", fontSize: 14, color: "var(--text-primary)", fontWeight: 600, cursor: "pointer", padding: "6px 12px", display: "flex", alignItems: "center", gap: 4 },
  menuBtn: { background: "none", border: "none", fontSize: 24, cursor: "pointer", display: "flex", alignItems: "center", color: "var(--text-primary)" },
  searchBox: { margin: "0 16px 12px", background: "var(--bg-secondary)", borderRadius: 12, display: "flex", alignItems: "center", padding: "12px 16px", gap: 10, color: "var(--text-muted)" },
  searchInput: { border: "none", background: "none", outline: "none", fontSize: 16, flex: 1, color: "var(--text-primary)" },
  categories: { display: "flex", gap: 8, padding: "0 16px 16px", overflowX: "auto" },
  catBtn: { background: "none", border: "none", fontSize: 15, color: "var(--text-secondary)", cursor: "pointer", padding: "8px 20px", borderRadius: 20, whiteSpace: "nowrap", transition: "all 0.2s ease", fontWeight: 400 },
  catActive: { background: "var(--accent)", color: "#fff", border: "none", fontSize: 15, cursor: "pointer", padding: "8px 20px", borderRadius: 20, fontWeight: 600, whiteSpace: "nowrap", transition: "all 0.2s ease" },
  sectionTitle: { fontSize: 28, fontWeight: 700, padding: "0 16px 16px", margin: 0, color: "var(--text-primary)" },
  grid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, padding: "0 16px" },
  card: { cursor: "pointer" },
  cardImageWrap: { position: "relative", borderRadius: 16, overflow: "hidden", aspectRatio: "1", background: "var(--bg-secondary)" },
  cardImage: { width: "100%", height: "100%", objectFit: "cover" },
  addBtn: { position: "absolute", bottom: 8, right: 8, width: 40, height: 40, borderRadius: "50%", background: "var(--bg-primary)", border: "none", fontSize: 24, cursor: "pointer", boxShadow: "0 2px 8px rgba(0,0,0,0.15)", display: "flex", alignItems: "center", justifyContent: "center", transition: "transform 0.2s ease", animation: "scaleIn 0.3s ease", color: "var(--text-primary)" },
  cardCounter: { position: "absolute", bottom: 8, left: 8, right: 8, display: "flex", alignItems: "center", justifyContent: "space-between", background: "var(--bg-primary)", borderRadius: 24, padding: "4px 8px", boxShadow: "0 2px 8px rgba(0,0,0,0.15)", animation: "scaleIn 0.3s ease" },
  counterBtn: { background: "none", border: "none", fontSize: 20, cursor: "pointer", padding: "4px 12px", color: "var(--text-primary)", transition: "transform 0.1s ease" },
  counterNum: { fontSize: 16, fontWeight: 600 },
  cardPrice: { fontSize: 20, fontWeight: 700, marginTop: 8, color: "var(--text-primary)" },
  cardName: { fontSize: 13, color: "var(--text-muted)", textTransform: "uppercase", letterSpacing: 0.5 },
  cartBar: { position: "fixed", bottom: 0, left: "50%", transform: "translateX(-50%)", width: "100%", maxWidth: 480, background: "var(--bg-primary)", borderTop: "1px solid var(--border-color)", padding: "12px 16px", zIndex: 100 },
  cartInfo: { display: "flex", justifyContent: "space-between", fontSize: 15, color: "var(--text-primary)", marginBottom: 8 },
  cartButton: { width: "100%", background: "var(--accent)", color: "#fff", border: "none", borderRadius: 12, padding: "16px", fontSize: 17, fontWeight: 600, cursor: "pointer", display: "flex", justifyContent: "space-between", transition: "background 0.2s ease" },
  modalOverlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.5)", zIndex: 200, display: "flex", flexDirection: "column", justifyContent: "flex-end", animation: "fadeIn 0.3s ease" },
  modal: { background: "var(--bg-primary)", borderRadius: "20px 20px 0 0", maxHeight: "90vh", overflow: "auto", maxWidth: 480, width: "100%", margin: "0 auto", animation: "slideUp 0.3s ease" },
  modalImageWrap: { position: "relative", width: "100%", aspectRatio: "1", background: "var(--bg-secondary)" },
  modalImage: { width: "100%", height: "100%", objectFit: "cover" },
  modalFav: { position: "absolute", top: 16, left: 16, width: 44, height: 44, borderRadius: "50%", background: "var(--bg-primary)", border: "none", cursor: "pointer", color: "var(--accent)", boxShadow: "0 2px 8px rgba(0,0,0,0.1)", display: "flex", alignItems: "center", justifyContent: "center", transition: "transform 0.2s ease" },
  modalClose: { position: "absolute", top: 16, right: 16, width: 44, height: 44, borderRadius: "50%", background: "var(--bg-primary)", border: "none", cursor: "pointer", color: "var(--text-primary)", boxShadow: "0 2px 8px rgba(0,0,0,0.1)", display: "flex", alignItems: "center", justifyContent: "center", transition: "transform 0.2s ease" },
  modalBody: { padding: "20px 16px 32px" },
  modalTitle: { fontSize: 24, fontWeight: 700, margin: "0 0 8px", color: "var(--text-primary)" },
  modalDesc: { fontSize: 15, color: "var(--text-secondary)", margin: "0 0 12px", lineHeight: 1.5 },
  modalPrice: { fontSize: 22, fontWeight: 700, color: "var(--text-primary)", margin: "0 0 20px" },
  modalCounter: { display: "inline-flex", alignItems: "center", gap: 0, background: "var(--bg-secondary)", borderRadius: 30, overflow: "hidden" },
  counterBtnLg: { background: "none", border: "none", fontSize: 22, cursor: "pointer", padding: "10px 20px", color: "var(--text-primary)", transition: "background 0.2s ease" },
  counterNumLg: { fontSize: 18, fontWeight: 600, minWidth: 30, textAlign: "center", color: "var(--text-primary)" },
  cartHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "16px 0", borderBottom: "none" },
  backBtn: { background: "none", border: "none", fontSize: 24, cursor: "pointer", color: "var(--text-primary)", padding: 0, display: "flex", alignItems: "center" },
  clearCartBtn: { display: "flex", alignItems: "center", gap: 6, background: "none", border: "1px solid var(--border-color)", borderRadius: 24, padding: "8px 16px", cursor: "pointer", color: "var(--accent)", transition: "all 0.2s ease" },
  cartItem: { display: "flex", alignItems: "center", gap: 12, padding: "16px 0", borderBottom: "1px solid var(--border-color)" },
  cartItemImage: { width: 80, height: 80, borderRadius: 12, objectFit: "cover", background: "var(--bg-secondary)" },
  cartItemControls: { display: "flex", alignItems: "center", gap: 8 },
  cartControlBtn: { width: 40, height: 40, borderRadius: "50%", background: "none", border: "1px solid var(--border-color)", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", color: "#2d5a3d", transition: "all 0.2s ease" },
  cartControlBtnPlus: { width: 40, height: 40, borderRadius: "50%", background: "none", border: "1px solid var(--border-color)", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 20, color: "var(--text-primary)", transition: "all 0.2s ease" },
  homeFab: { position: "fixed", bottom: 160, left: 20, width: 56, height: 56, borderRadius: "50%", background: "var(--accent)", color: "#fff", border: "none", cursor: "pointer", boxShadow: "0 4px 12px rgba(45,90,61,0.4)", zIndex: 99, display: "flex", alignItems: "center", justifyContent: "center", transition: "transform 0.2s ease" },
  menuOverlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.4)", zIndex: 300, display: "flex", justifyContent: "flex-end", animation: "fadeIn 0.3s ease" },
  menuPanel: { width: "85%", maxWidth: 400, background: "var(--bg-primary)", height: "100%", display: "flex", flexDirection: "column", overflow: "hidden", padding: "24px 20px", animation: "slideInRight 0.3s ease" },
  menuHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 },
  menuCloseBtn: { background: "none", border: "none", fontSize: 24, cursor: "pointer", color: "var(--text-primary)", display: "flex", alignItems: "center" },
  menuList: { flex: 1, overflowY: "auto", minHeight: 0 },
  menuItem: { display: "flex", alignItems: "center", gap: 16, padding: "16px 0", background: "none", border: "none", cursor: "pointer", width: "100%", transition: "opacity 0.2s ease", color: "var(--text-primary)" },
  menuItemRow: { display: "flex", alignItems: "center", gap: 16, padding: "16px 0", color: "var(--text-primary)" },
  menuDivider: { height: 1, background: "var(--border-color)" },
  languageModal: { background: "var(--bg-primary)", borderRadius: "20px 20px 0 0", maxHeight: "70vh", overflow: "auto", maxWidth: 480, width: "100%", margin: "auto auto 0", animation: "slideUp 0.3s ease" },
  languageHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "20px 20px 16px", borderBottom: "1px solid var(--border-color)" },
  modalCloseBtn: { background: "none", border: "none", fontSize: 24, cursor: "pointer", color: "var(--text-primary)", display: "flex", alignItems: "center", padding: 0 },
  languageList: { padding: "8px 0" },
  languageItem: { width: "100%", display: "flex", alignItems: "center", gap: 16, padding: "18px 20px", background: "none", border: "none", cursor: "pointer", transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)", color: "var(--text-primary)", textAlign: "left" },
  languageItemActive: { width: "100%", display: "flex", alignItems: "center", gap: 16, padding: "18px 20px", background: "var(--accent-light)", border: "none", cursor: "pointer", transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)", color: "var(--text-primary)", textAlign: "left", transform: "scale(1.02)" },
  languageIconCircle: { width: 48, height: 48, borderRadius: "50%", background: "var(--bg-secondary)", display: "flex", alignItems: "center", justifyContent: "center", color: "var(--accent)", flexShrink: 0 },
  orderTypeModal: { background: "var(--bg-primary)", borderRadius: "20px 20px 0 0", maxHeight: "70vh", overflow: "auto", maxWidth: 480, width: "100%", margin: "auto auto 0", animation: "slideUp 0.3s ease" },
  orderTypeHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "20px 20px 16px", borderBottom: "1px solid var(--border-color)" },
  orderTypeList: { padding: "16px 20px" },
  orderTypeItem: { width: "100%", display: "flex", alignItems: "center", gap: 16, padding: "20px", background: "var(--bg-primary)", border: "2px solid var(--border-color)", borderRadius: 16, cursor: "pointer", transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)", marginBottom: 12, textAlign: "left" },
  orderTypeItemActive: { width: "100%", display: "flex", alignItems: "center", gap: 16, padding: "20px", background: "var(--accent-light)", border: "2px solid var(--accent)", borderRadius: 16, cursor: "pointer", transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)", marginBottom: 12, textAlign: "left", transform: "scale(1.02)", boxShadow: "0 4px 12px rgba(45, 90, 61, 0.15)" },
  orderTypeIcon: { width: 48, height: 48, borderRadius: 12, background: "var(--bg-secondary)", display: "flex", alignItems: "center", justifyContent: "center", color: "var(--accent)", flexShrink: 0 },
  branchModal: { background: "var(--bg-primary)", borderRadius: "20px 20px 0 0", maxHeight: "80vh", overflow: "auto", maxWidth: 480, width: "100%", margin: "auto auto 0", animation: "slideUp 0.3s ease" },
  branchHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "20px 20px 16px", borderBottom: "1px solid var(--border-color)" },
  branchList: { padding: "8px 0" },
  branchItem: { width: "100%", display: "flex", alignItems: "center", gap: 16, padding: "18px 20px", background: "none", border: "none", borderBottom: "1px solid var(--border-color)", cursor: "pointer", transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)", color: "var(--text-primary)", textAlign: "left" },
  branchItemActive: { width: "100%", display: "flex", alignItems: "center", gap: 16, padding: "18px 20px", background: "var(--accent-light)", border: "none", borderBottom: "1px solid var(--border-color)", cursor: "pointer", transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)", color: "var(--text-primary)", textAlign: "left", transform: "translateX(4px)" },
  branchIcon: { width: 44, height: 44, borderRadius: 12, background: "var(--bg-secondary)", display: "flex", alignItems: "center", justifyContent: "center", color: "var(--accent)", flexShrink: 0 },
  myLocationBtn: { position: "absolute", bottom: 16, right: 16, width: 48, height: 48, borderRadius: "50%", background: "#fff", border: "none", cursor: "pointer", boxShadow: "0 2px 8px rgba(0,0,0,0.2)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 1000 },
  locationModal: { background: "var(--bg-primary)", borderRadius: "20px 20px 0 0", maxHeight: "90vh", overflow: "hidden", maxWidth: 480, width: "100%", margin: "auto auto 0", animation: "slideUp 0.3s ease" },
  scrollTopBtn: { position: "fixed", bottom: 160, right: 20, width: 56, height: 56, borderRadius: "50%", background: "var(--accent)", color: "#fff", border: "none", cursor: "pointer", boxShadow: "0 4px 12px rgba(45,90,61,0.4)", zIndex: 99, display: "flex", alignItems: "center", justifyContent: "center", transition: "all 0.3s ease", animation: "scaleIn 0.3s ease" },
};
